In [2]:
from keras.models import load_model
import numpy as np
from ai import AI
ai = AI(0, "")
path = ""
ModelFileName = f"{path}model.h5"
# ai.load_model()

model = load_model(ModelFileName)
print("testing")
print(model)



testing


In [3]:
for layer in model.layers:
    print(layer.name, layer.weights)

masking []
lstm [<tf.Variable 'lstm/lstm_cell_2/kernel:0' shape=(2, 64) dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)>, <tf.Variable 'lstm/lstm_cell_2/recurrent_kernel:0' shape=(16, 64) dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0.

In [5]:
for i, v in enumerate(model.trainable_weights):
    print(i)
    print(v)

0
<tf.Variable 'lstm/lstm_cell_2/kernel:0' shape=(2, 64) dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)>
1
<tf.Variable 'lstm/lstm_cell_2/recurrent_kernel:0' shape=(16, 64) dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0.,

In [6]:
print(model.layers[1].weights[0])

<tf.Variable 'lstm/lstm_cell_2/kernel:0' shape=(2, 64) dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
      dtype=float32)>


In [7]:
test = model.layers[1].weights[0]

In [8]:
my_list = test[0].numpy().tolist()
print(my_list)


[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


In [9]:
for layer in model.layers:
    print('hey', len(layer.trainable_weights))
    for weight in layer.weights:
        print(weight.get_shape())
        for elem in weight:
            # print(elem)
            pass

hey 0
hey 3
(2, 64)
(16, 64)
(64,)
hey 0
hey 2
(16, 96)
(96,)
hey 0


In [10]:
def tf_weights_to_list(model):
    """converts a the weights of a model in to a 1D list"""
    my_list = []
    for layer in model.layers:
        for weight in layer.weights:
            if len(weight.get_shape()) == 2:
                for elem in weight:
                    my_list.extend(elem.numpy().tolist())
            elif len(weight.get_shape()) == 1:
                my_list.extend(weight.numpy().tolist())
            else:
                print("error, there is a shape of weigths that was not expected")
    return my_list
my_list = tf_weights_to_list(model)
print(len(my_list))
print(my_list)


2848
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,

In [11]:
def get_model_shape(model):
    """
    Returns a list which contains for each layer it's shape. 
    The shape is a tuple containing either 1 or 2 elem.
    """
    my_list = []
    for layer in model.layers:
        my_list.extend(tuple(weight.get_shape()) for weight in layer.weights)
    return my_list
shapes = get_model_shape(model)
for elem in shapes:
    print(len(elem))
print(get_model_shape(model))


2
2
1
2
1
[(2, 64), (16, 64), (64,), (16, 96), (96,)]


In [12]:
zeros = list(range(len(my_list)))

def reshape_list(shapes, my_list):
    """reshapes the list in the number of list that should be set 

    Args:
        shapes (_type_): _description_
        my_list (_type_): _description_

    Returns:
        _type_: _description_
    """
    i=0
    new_list = []
    for elem in shapes:
        if len(elem) == 1:
            new_list.append(np.array(my_list[i:i+elem[0]]))
            i += elem[0]
        elif len(elem) == 2:
            temp = []
            for _ in range(elem[0]):
                temp.append(my_list[i:i+elem[1]])
                i += elem[1]
            new_list.append(np.array(temp))
    first = new_list[:3]
    second = new_list[3:]
    return [first, second]
shaped = reshape_list(shapes, zeros)
print(len(shaped))
print(shaped[1][0].shape)
print(shaped)




2
(16, 96)
[[array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63],
       [ 64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
         77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
         90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127]]), array([[ 128,  129,  130, ...,  189,  190,  191],
       [ 192,  193,  194, ...,  253,  254,  255],
       [ 256,  257,  258, ...,  317,  318,  319],
       ...,
       [ 960,  961,  962, ..., 1021, 1022, 1023],
       [1024, 1025, 1026, ..., 1085, 1086, 1087],
 

In [13]:
def list_to_tf_weights(model, list_of_weights):
    shapes = get_model_shape(model)
    reshaped = reshape_list(shapes, list_of_weights)
    i = 0
    for layer in model.layers:
        print(layer)
        for weight in layer.weights:
            # print(weight)
            layer.set_weights(reshaped[i])
            print(i)
            i += 1
            break
    # model.set_weights(reshaped)
    return model

print(tf_weights_to_list(list_to_tf_weights(model, zeros)))


0
1
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0, 65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0, 74.0, 75.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0, 92.0, 93.0, 94.0, 95.0, 96.0, 97.0, 98.0, 99.0, 100.0, 101.0, 102.0, 103.0, 104.0, 105.0, 106.0, 107.0, 108.0, 109.0, 110.0, 111.0, 112.0, 113.0, 114.0, 115.0, 116.0, 117.0, 118.0, 119.0, 120.0, 121.0, 122.0, 123.0, 124.0, 125.0, 126.0, 127.0, 128.0, 129.0, 130.0, 131.0, 132.0, 133.0, 134.0, 135.0, 136.0, 137.0, 138.0, 139.0, 140.0, 141.0, 142.0, 143.0, 144.0, 145.0, 146.0, 147.0, 148.0, 149.0, 150.0, 151.0, 152.0, 153.0, 154.0, 155.0, 156.0, 157.0,

In [2]:
print([9999999999-i for i in range(2848)])

[9999999999, 9999999998, 9999999997, 9999999996, 9999999995, 9999999994, 9999999993, 9999999992, 9999999991, 9999999990, 9999999989, 9999999988, 9999999987, 9999999986, 9999999985, 9999999984, 9999999983, 9999999982, 9999999981, 9999999980, 9999999979, 9999999978, 9999999977, 9999999976, 9999999975, 9999999974, 9999999973, 9999999972, 9999999971, 9999999970, 9999999969, 9999999968, 9999999967, 9999999966, 9999999965, 9999999964, 9999999963, 9999999962, 9999999961, 9999999960, 9999999959, 9999999958, 9999999957, 9999999956, 9999999955, 9999999954, 9999999953, 9999999952, 9999999951, 9999999950, 9999999949, 9999999948, 9999999947, 9999999946, 9999999945, 9999999944, 9999999943, 9999999942, 9999999941, 9999999940, 9999999939, 9999999938, 9999999937, 9999999936, 9999999935, 9999999934, 9999999933, 9999999932, 9999999931, 9999999930, 9999999929, 9999999928, 9999999927, 9999999926, 9999999925, 9999999924, 9999999923, 9999999922, 9999999921, 9999999920, 9999999919, 9999999918, 9999999917, 999

initialisation cost : negligeable if zeros, todo if random
setting first weights = 
    gas	                14 780 492 gas
    transaction cost	12 852 601 gas 
    execution cost	    12 296 245 gas
setting middle weights = 
    gas	                 7 428 734 gas
    transaction cost	 6 459 768 gas 
    execution cost	     5 903 412 gas
setting last weights = 
    gas	                19 507 739 gas
    transaction cost	16 963 251 gas 
    execution cost	    16 406 895 gas

execution cost of getWeights : 2 715 764 gas

In [14]:
for layer in model.layers:
    print(layer.name, layer.weights)

masking []
lstm [<tf.Variable 'lstm/lstm_cell_2/kernel:0' shape=(2, 64) dtype=float32, numpy=
array([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
         22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
         33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
         44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
         55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.],
       [ 64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,
         75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,
         86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,
         97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106., 107.,
        108., 109., 110., 111., 112., 113., 114., 115., 116., 117., 118.,
        119., 120., 121., 122., 123., 124., 125., 126., 127.]],
      dtype=float32)>, <tf.Variable 'ls